name: "Ya2DLNA Streaming"
version: "1.0.0"
slug: "ya2dlna"
description: "Stream audio from Yandex Station to DLNA device"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
host_network: true
ports:
  8000/tcp: 8000
  8001/tcp: 8001
map:
  - config:rw
logo: "logo.png"
options:
  local_server_port_dlna: 8001
  local_server_port_api: 8000
  debug: false
schema:
  local_server_port_dlna: int
  local_server_port_api: int
  debug: bool

build_from:
  aarch64: homeassistant/aarch64-base:latest
  amd64: homeassistant/amd64-base:latest
